service: api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  api:
    handler: server.server
    events:
      - http:
          path: words
          method: get
          cors: true