service: api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: words
          method: get
          cors: true
      - http:
          path: words
          method: post
          cors: true
      - http:
          path: words
          method: options
          cors: true
      - http:
          path: health
          method: get
          cors: true
      - http:
          path: health
          method: options
          cors: true